server:
  shutdown: graceful
  port: 8080

spring:
  application:
    name: polygon
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://${DB_HOST}?prepareThreshold=1&preparedStatementCacheSizeMiB=10&reWriteBatchedInserts=true&currentSchema=public
    username: ${DB_APP_USERNAME}
    password: ${DB_APP_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        format_sql: false
        use_sql_comments: false
        default_batch_fetch_size: 25
  flyway:
    enabled: true
    locations: classpath:db/migration
    driver-class-name: org.postgresql.Driver
    default-schema: public
    schemas: public
    validate-migration-naming: true
